default: &DEFAULT
# Dataset params
  data_dir: '/home/cmarasinou/Documents/Data/INbreast-pytorch/'
  img_format: 'png16'
  csv: 'val_by_patient_20.csv'
# Output params
  save_dir: '/home/cmarasinou/Documents/Projects/mammography/output/context/preds/'
  model_name: 'context1'
  thr_list: [0.1, 0.2,0.3,0.4, 0.5, 0.6, 0.7, 0.9, 0.95, 0.99, 0.999, 0.9999, 0.99999, 0.999999, 0.9999999, 0.99999999]
  #thr_list: [ 0.999999, 0.9999999, 0.99999999]
  #thr_list: [0.0, 0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
# DoG params
  DoG_only: False
  DoG_thr: 0.01
  min_sigma: 1.6
  max_sigma: 2.0
  overlap: 0.0
# Confusion matrix generation params
  small_area: 1
  iou_thr: 0.3
  distance_thr: 5
  evaluate_dots_separately: True
# Inference params
  batch_size: 256
  out_csv: 'context1'
  gpu_number: 0